version: '3.8'

services:
  kanban-mcp-attachments:
    image: kanban-mcp-attachments:latest
    container_name: kanban-mcp-attachments
    environment:
      - PLANKA_BASE_URL=${PLANKA_BASE_URL:-http://localhost:3333}
      - PLANKA_AGENT_EMAIL=${PLANKA_AGENT_EMAIL:-demo@demo.demo}
      - PLANKA_AGENT_PASSWORD=${PLANKA_AGENT_PASSWORD:-demo}
    volumes:
      # Mount attachment directory
      - ./attachments:/app/attachments
    ports:
      - "3008:3008"
    networks:
      - marcus-network
    restart: unless-stopped

networks:
  marcus-network:
    external: true
