"""Regression test: spec_coverage gap tasks must be dependencies of integration verification.

snake_game-v2 [2-agent] experiment exposed an ordering bug where
spec_gap tasks ran concurrently with the integration verification
task, defeating the "verify everything together at the end" contract.

Root cause: ``check_spec_coverage`` ran AFTER
``enhance_project_with_integration`` in
``src.integrations.nlp_tools.NaturalLanguageProjectCreator.process_natural_language``,
so gap tasks were appended to the task list after integration's
dependency snapshot was taken. This meant:

  - Integration verification's deps did NOT include gap tasks
  - Gap tasks had no dependents pointing to them
  - Integration could complete (or run concurrently) while gap
    tasks were still TODO/in-progress
  - Documentation task (which depends on integration) could similarly
    fire before gap tasks finished

Fix (PR #...): move ``check_spec_coverage`` to run BEFORE
``enhance_project_with_integration`` so gap tasks are in the task
list when integration computes its dependency snapshot.

This test pins the contract: any task generated by spec_coverage MUST
be in the integration verification task's ``dependencies``.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from src.core.models import Priority, Task, TaskStatus
from src.integrations.integration_verification import (
    enhance_project_with_integration,
)
from src.integrations.spec_coverage import check_spec_coverage

pytestmark = pytest.mark.unit


def _make_impl_task(name: str, task_id: str | None = None) -> Task:
    """Build a minimal implementation task fixture."""
    now = datetime.now(timezone.utc)
    return Task(
        id=task_id or f"task-{name.replace(' ', '-')}",
        name=name,
        description=f"Implement {name}",
        status=TaskStatus.TODO,
        priority=Priority.MEDIUM,
        assigned_to=None,
        created_at=now,
        updated_at=now,
        due_date=None,
        estimated_hours=2.0,
        labels=["type:implementation"],
        dependencies=[],
    )


class TestSpecCoverageBeforeIntegrationOrder:
    """Spec gap tasks must precede the integration task in the pipeline."""

    @pytest.mark.asyncio
    async def test_gap_tasks_are_dependencies_of_integration_when_added_first(
        self,
    ) -> None:
        """When spec_coverage runs first, integration's deps include gap tasks.

        This is the post-fix order. The integration verification task
        must depend on every gap task so it doesn't fire until they
        finish.
        """
        # Pre-existing implementation tasks
        existing = [
            _make_impl_task("Snake Movement"),
            _make_impl_task("Food Spawning"),
        ]

        # Synthesize gap tasks for uncovered spec features. Patch the
        # internal LLM-extraction step so the test is deterministic.
        with (
            patch(
                "src.integrations.spec_coverage.extract_spec_features",
                new=AsyncMock(
                    return_value=[
                        "snake_movement",
                        "food_spawning",
                        "score_tracking",  # this one is uncovered
                    ]
                ),
            ),
        ):
            gap_tasks = await check_spec_coverage(
                description="Snake game with movement, food, and score",
                tasks=existing,
                project_name="snake-game",
            )

        assert len(gap_tasks) >= 1, "at least one gap task expected for this fixture"

        # New (correct) order: gap tasks merged BEFORE integration enhancement
        with_gaps = existing + gap_tasks
        enhanced = enhance_project_with_integration(
            with_gaps,
            project_description="Snake game",
            project_name="snake-game",
        )

        # Find the integration task
        integration_tasks = [
            t for t in enhanced if "type:integration" in (t.labels or [])
        ]
        assert (
            len(integration_tasks) == 1
        ), "Exactly one integration verification task expected after enhancement"
        integration_task = integration_tasks[0]

        # Every gap task MUST be a dependency of integration verification
        gap_ids = {t.id for t in gap_tasks}
        deps = set(integration_task.dependencies or [])
        missing = gap_ids - deps
        assert not missing, (
            f"Integration verification is missing {len(missing)} gap task(s) as "
            f"dependencies: {missing}. spec_coverage must run BEFORE "
            f"enhance_project_with_integration so gap tasks are visible when "
            f"integration computes its dependency snapshot."
        )

    @pytest.mark.asyncio
    async def test_gap_tasks_NOT_dependencies_when_added_after_integration(
        self,
    ) -> None:
        """Reverse-order baseline (the bug): demonstrates the failure mode.

        When spec_coverage runs AFTER integration, gap tasks are
        appended to the task list but integration's dependency list
        was already frozen — so gap tasks are NOT dependencies.
        """
        existing = [
            _make_impl_task("Snake Movement"),
            _make_impl_task("Food Spawning"),
        ]

        # Old (buggy) order: integration first, then gap tasks appended
        enhanced = enhance_project_with_integration(
            existing,
            project_description="Snake game",
            project_name="snake-game",
        )

        with patch(
            "src.integrations.spec_coverage.extract_spec_features",
            new=AsyncMock(
                return_value=["snake_movement", "food_spawning", "score_tracking"]
            ),
        ):
            gap_tasks = await check_spec_coverage(
                description="Snake game with movement, food, and score",
                tasks=enhanced,
                project_name="snake-game",
            )

        # Append gap tasks AFTER integration — the buggy order
        with_gaps_after = enhanced + gap_tasks

        integration_task = next(
            t for t in with_gaps_after if "type:integration" in (t.labels or [])
        )
        gap_ids = {t.id for t in gap_tasks}
        deps = set(integration_task.dependencies or [])

        # Pinning the bug: in this (wrong) order, gap tasks are NOT in
        # integration's deps. The fix is to never use this order.
        assert gap_tasks, "fixture must produce at least one gap task"
        assert not (gap_ids & deps), (
            "Bug-pinning baseline: gap tasks added AFTER integration "
            "must be excluded from its deps (this is the failure mode "
            "the production fix addresses by reversing the order)."
        )
